[workspace]
members = ["mashi-cli", "mashi-core", "mashi-test-suite", "xtask"]
resolver = "3"

[workspace.package]
authors = ["sagacity", "ferris"]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
anyhow = "1.0.100"
clap = { version = "4", features = ["derive"] }
indicatif = "0.18.3"
wast = "244.0.0"
zopfli = "0.8.3"

[profile.dev.package.mashi-core]
# Enable the following to make the test suite run faster, at the expense of debuggability
opt-level = 3

[profile.dev.package.wast]
opt-level = 3

[profile.tiny]
inherits = "release"
strip = true
opt-level = "s"
lto = true
codegen-units = 1