[package]
name = "mashi-core"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
log = "0.4.29"
wasmi = { version = "1.0.8", features = ["simd"] }
wasmparser = "0.245.0"

[dev-dependencies]
log4rs = "1.4.0"
num-traits = "0.2.19"
rand = "0.10.0"
